### ISSUE TITLE
Error: The template is not valid.

### ISSUE THREAD

**Issue by gharot** [PhutureCorp/ecr-login-token-action#115]
#### Steps to reproduce this issue

1. Set secrets in repository
2. Copy paste example
3. run-it

#### Expected behaviour

> The workflow performs the job successfully 

#### Actual behaviour

> Workflow crashes on error 

> Error: The template is not valid. .github/workflows/ecr-login.yaml (Line: 26, Col: 19): Unexpected value ''

```yml
name: Build using Amazon ECR Container

on:
  workflow_dispatch:

jobs:
  login:
    runs-on: self-hosted
    outputs:
      token: ${{ steps.ecr.outputs.token }}
    steps:
      -
        name: Get token to login to Amazon ECR
        uses: PhutureCorp/ecr-login-token@v0.8.0
        with:
          registry: XXX.dkr.ecr.YYY.amazonaws.com
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  build:
    runs-on: self-hosted
    needs: login
    container:
      image: XXX.dkr.ecr.YYY.amazonaws.com/ZZZ:UUU
      credentials:
        username: AWS
        password: ${{ needs.login.outputs.token }}
    steps:
    - name: Check out code
      uses: actions/checkout@v2
```
